### ISSUE TITLE
Rails 6 and camelCase

### ISSUE THREAD

**Issue by resistorsoftware** [vigetlabs/olive_branch#41]
My front-end calls a route /api/events where the index method returns some JSON for consumption on the front-end. Of course, there is a key in the JSON snake cased as pick_up. I would like to see that key as pickUp.

In my Rails 6 application.rb file I used the OliveGem config as follows:

     excluded_routes = ->(env) { !env["PATH_INFO"].match(%r{^/api}) }
     config.middleware.use OliveBranch::Middleware,
                      inflection:         "camel",
                      exclude_params:     excluded_routes,
                      exclude_response:   excluded_routes,
                      content_type_check: ->(content_type) { content_type == true }

When I make Axios requests to /api/events, the JSON being returned remains as snake-case. 

So my index method in the API is calling out to another API, and getting JSON back. And that JSON is snake-case. I am rendering in the index as 
    render json: data 

where data is the resulting JSON from that call to the third-party API. I have no data from any ActiveRecord models or anything. Hence jBuilder is of no use to me. 

I was under the impression that as Middleware, this gem would take care of ensuring conversion took place of JSON requests and responses. But I am not seeing that. What am I doing wrong?

**Comment by efatsi** [comment]
@resistorsoftware I'm not entirely sure (it's been a few years since I've set this up on a new project. The code you pasted was very recently added to the readme by another community member, it's possible that it's not a 100% perfect default. My guess is that the inflection method is not being run when the response data is going out.

Some things for you to try though:
- Try removing the `content_type_check:` line perhaps? Or replacing it with `content_type_check: ->(content_type) { true }`.
- `bundle open olive_branch` and stick a breakpoint above [this line](https://github.com/vigetlabs/olive_branch/blob/master/lib/olive_branch/middleware.rb#L63). You can then run the commands that are run in that method in an interactive console and see exactly what's that working as expected.

**Comment by efatsi** [comment]
Ah, I looked more closely at the code you pasted, `content_type == true` is not from the README, looks like you added that yourself. That's going to fail all the time since `content_type` is a string instead of a boolean. Removing or replacing that line with something more valid should fix your problem.
